In [1]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# %cd /content/drive/My\ Drive/

In [3]:

# !git clone https://github.com/huggingface/transformers


In [4]:
%cd /content/drive/My\ Drive/transformers/src/transformers

/content/drive/My Drive/transformers/src/transformers


In [5]:
!pip install -r requirements.txt
!pip install transformers

In [6]:
# 

In [7]:
# tokenizer.encode("Hello, my dog is cute", add_special_tokens=False)

In [8]:
!pip install wget

In [9]:
import tensorflow as tf

# Get the GPU device name.
device_name = tf.test.gpu_device_name()

# The device name should look like the following:
if device_name == '/device:GPU:0':
    print('Found GPU at: {}'.format(device_name))
else:
    raise SystemError('GPU device not found')

Found GPU at: /device:GPU:0


In [10]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla P4


In [11]:
import wget
import os
print('Downloading dataset...')

# The URL for the dataset zip file.
url = 'https://nyu-mll.github.io/CoLA/cola_public_1.1.zip'

# Download the file (if we haven't already)
if not os.path.exists('./cola_public_1.1.zip'):
    wget.download(url, './cola_public_1.1.zip')

In [12]:
if not os.path.exists('./cola_public/'):
    !unzip cola_public_1.1.zip

In [13]:
import pandas as pd

# Load the dataset into a pandas dataframe.
trans = pd.read_csv("transaction_final.csv")
trans=trans.groupby(['STORE_ID','WEEK_NO']).agg(lambda x:list(x)).reset_index()
product=pd.read_csv("products_final.csv")

# Report the number of sentences.
print('Number of assortment sets: {:,}\n'.format(trans.shape[0]))
print('Number of products: {:,}\n'.format(product.shape[0]))


# Display 10 random rows from the data.
print(trans.sample(10))
print(product.tail(10))
trans.head()

Number of assortment sets: 13,937

Number of products: 92,353

       STORE_ID  ...                                              INDEX
3588        335  ...  [6678, 25715, 25755, 29658, 35085, 35577, 9367...
10495       622  ...  [49464, 47022, 49180, 49250, 62933, 69197, 727...
12554      3287  ...  [2927, 544, 1635, 514, 1156, 66217, 3709, 424,...
488         289  ...  [38263, 29658, 13160, 29243, 12685, 14785, 195...
681         292  ...  [6678, 38263, 15968, 25715, 25755, 32779, 3557...
6576        380  ...  [38263, 25715, 25755, 35577, 25814, 17780, 229...
13042     31582  ...  [29658, 35577, 64106, 17780, 21117, 29410, 712...
3357        333  ...  [38263, 8717, 25715, 29658, 35577, 9960, 13160...
4410        346  ...  [18151, 38263, 9367, 17780, 34403, 11165, 2822...
8460        421  ...  [6678, 8895, 25755, 29658, 35577, 37360, 38132...

[10 rows x 5 columns]
       PRODUCT_ID  MANUFACTURER  ... CURR_SIZE_OF_PRODUCT  INDEX
92343    18273019          2223  ...              11.5 OZ

STORE_ID  WEEK_NO        PRODUCT_ID WEEK_QUANTITY         INDEX
0         1        5  [480014, 718226]     [7249, 1]  [4059, 5293]
1         1        6          [480014]        [2438]        [4059]
2         1       14         [6903760]           [1]       [58675]
3         2       41          [702733]           [1]        [5223]
4         2       93          [721164]           [1]        [5304]

In [14]:

assortment = trans.INDEX.values
# assortment=[product[product.PRODUCT_ID==25671].index[0] for i in range(len(assortment)) for j in assortment[i]]
labels = trans.WEEK_QUANTITY.values
assortment

array([list([4059, 5293]), list([4059]), list([58675]), ...,
       list([6678, 18151, 38263, 25715, 29658, 32779, 35577, 53098, 13160, 25814, 8282, 15137, 28845, 32710, 36751, 23070, 8093, 9070, 10425, 16016, 18006, 20974, 40584, 41176, 7700, 15398, 35460, 62070, 16864, 22061, 24467, 30630, 53125, 71200, 11259, 12657, 16607, 32073, 39228, 24251, 41194, 59493, 35574, 38616, 39582, 8723, 9206, 31145, 36965, 26316, 12238, 18194, 20654, 24951, 26209, 33726, 6689, 37475, 13068, 21570, 22187, 30716, 19223, 12168, 32045, 61224, 7113, 21816, 21172, 72641, 15431, 32979, 16656, 30576, 20441, 34160, 23373, 52957, 17111, 30648, 9139, 20879, 25096, 11868, 21968, 30991, 38688, 27918, 32949, 75495, 27441, 31193, 16119, 41694, 11514, 16040, 24962, 14938, 28694, 20490, 21352, 52608, 7711, 25098, 32588, 40155, 22717, 38365, 75312, 25591, 33553, 34645, 15051, 38632, 38878, 69964, 33043, 67228, 20351, 5938, 14808, 24745, 10759, 41180, 15839, 30871, 33968, 19771, 39012, 53992, 6566, 19088, 36413, 59802, 1

In [15]:

# Print the sample Assortment.
print(' Assortment: ', assortment[29])

# Print the corresponding label set.
print('Labels: ', labels[29])



 Assortment:  [4592, 4472, 3872, 3889, 4537, 4624, 4652, 4691, 4746, 4831, 4888, 5014, 5404, 5440, 5638]
Labels:  [1, 2, 3, 2, 2, 2, 1, 4, 6, 1, 1, 2, 1, 1, 2]


In [16]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')


In [17]:
  import numpy as np
# ass=np.concatenate(assortment).astype(None)
assortment

array([list([4059, 5293]), list([4059]), list([58675]), ...,
       list([6678, 18151, 38263, 25715, 29658, 32779, 35577, 53098, 13160, 25814, 8282, 15137, 28845, 32710, 36751, 23070, 8093, 9070, 10425, 16016, 18006, 20974, 40584, 41176, 7700, 15398, 35460, 62070, 16864, 22061, 24467, 30630, 53125, 71200, 11259, 12657, 16607, 32073, 39228, 24251, 41194, 59493, 35574, 38616, 39582, 8723, 9206, 31145, 36965, 26316, 12238, 18194, 20654, 24951, 26209, 33726, 6689, 37475, 13068, 21570, 22187, 30716, 19223, 12168, 32045, 61224, 7113, 21816, 21172, 72641, 15431, 32979, 16656, 30576, 20441, 34160, 23373, 52957, 17111, 30648, 9139, 20879, 25096, 11868, 21968, 30991, 38688, 27918, 32949, 75495, 27441, 31193, 16119, 41694, 11514, 16040, 24962, 14938, 28694, 20490, 21352, 52608, 7711, 25098, 32588, 40155, 22717, 38365, 75312, 25591, 33553, 34645, 15051, 38632, 38878, 69964, 33043, 67228, 20351, 5938, 14808, 24745, 10759, 41180, 15839, 30871, 33968, 19771, 39012, 53992, 6566, 19088, 36413, 59802, 1

In [18]:
from keras.preprocessing.sequence import pad_sequences
MAX_LEN = 400

print('\nPadding/truncating all assortments to %d values...' % MAX_LEN)
product_tokens= pad_sequences(assortment, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")
demand_labels= pad_sequences(labels, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")

print('\nDone.')

Using TensorFlow backend.



Padding/truncating all assortments to 400 values...

Done.


In [19]:
attention_masks = []

# For each assortment...
for sent in product_tokens:
    
    # Create the attention mask.
    #   - If a token ID is 0, then it's padding, set the mask to 0.
    #   - If a token ID is > 0, then it's a real token, set the mask to 1.
    att_mask = [int(token_id > 0) for token_id in sent]
    
    # Store the attention mask for this sentence.
    attention_masks.append(att_mask)

In [20]:


trans['PRODUCT_ID']

0                                         [480014, 718226]
1                                                 [480014]
2                                                [6903760]
3                                                 [702733]
4                                                 [721164]
                               ...                        
13932    [926905, 1106523, 879755, 994928, 995242, 1029...
13933    [926905, 1106523, 995242, 1006878, 1029743, 10...
13934    [826249, 926905, 1106523, 994928, 1029743, 105...
13935    [879755, 995242, 1006878, 1029743, 1055863, 10...
13936    [826249, 926905, 1106523, 995242, 1029743, 108...
Name: PRODUCT_ID, Length: 13937, dtype: object

In [21]:


from sklearn.model_selection import train_test_split
train_inputs, validation_inputs, train_labels, validation_labels = train_test_split(product_tokens, demand_labels, 
                                                            random_state=2018, test_size=0.1)
train_masks, validation_masks, _, _ = train_test_split(attention_masks, labels,
                                             random_state=2018, test_size=0.1)

In [22]:
product_tokens

array([[ 4059,  5293,     0, ...,     0,     0,     0],
       [ 4059,     0,     0, ...,     0,     0,     0],
       [58675,     0,     0, ...,     0,     0,     0],
       ...,
       [ 6678, 18151, 38263, ...,     0,     0,     0],
       [12765, 25755, 27079, ..., 59639, 34200, 87413],
       [ 6678, 18151, 38263, ..., 91675, 91818, 91998]])

In [23]:
import torch
train_inputs = torch.tensor(train_inputs)
validation_inputs = torch.tensor(validation_inputs)

train_labels = torch.tensor(train_labels)
validation_labels = torch.tensor(validation_labels)

train_masks = torch.tensor(train_masks)
validation_masks = torch.tensor(validation_masks)


In [27]:
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
batch_size = 64

train_data = TensorDataset(train_inputs, train_masks, train_labels)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)

validation_data = TensorDataset(validation_inputs, validation_masks, validation_labels)
validation_sampler = SequentialSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)


In [36]:
x=np.arange(10)
y=torch.tensor(x)
y.view(1,-1)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# from modeling_bert import ProductBert
# model = ProductBert.from_pretrained(
#     "bert-base-uncased", # Use the 12-layer BERT model, with an uncased vocab.
#     num_labels = 1 # The number of output labels--2 for binary classification.
#     #                 # You can increase this for multi-class tasks.   
#     # output_attentions = False, # Whether the model returns attentions weights.
#     # output_hidden_states = True, # Whether the model returns all hidden-states.
# )
from modeling_bert import BertForTokenClassifications,BertConfig

from transformers import BertTokenizer
import torch

configuration = BertConfig()


tokenizer = BertTokenizer.from_pretrained('bert-base-uncased',num_labels=1)
model = BertForTokenClassifications(configuration)

input_ids = torch.tensor(assortment[11]).unsqueeze(0)  # Batch size 1
labels = torch.tensor([1] * input_ids.size(1)).unsqueeze(0)  # Batch size 1
print(input_ids)
print(labels)
print(input_ids.size(1))

outputs = model(input_ids=input_ids, labels=labels)

labels=torch.tensor([([1]*400)])
for step, batch in enumerate(train_dataloader):
  print(batch[2].size(0))
  print(batch[2])
  print(labels)
  outputs = model(input_ids=batch[0],token_type_ids=None, attention_mask=batch[1], labels=labels)
  break
outputs


tensor([[5189, 5238, 5379, 5595]])
tensor([[1, 1, 1, 1]])
4
64
tensor([[1, 6, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 3, 1,  ..., 0, 0, 0],
        [1, 2, 1,  ..., 0, 0, 0]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [26]:
model.cuda()

BertForTokenClassifications(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(92353, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwi

In [27]:
params = list(model.named_parameters())
params = list(model.named_parameters())

print('The BERT model has {:} different named parameters.\n'.format(len(params)))

print('==== Embedding Layer ====\n')

for p in params[0:5]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

print('\n==== First Transformer ====\n')

for p in params[5:21]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

print('\n==== Output Layer ====\n')

for p in params[-4:]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))


The BERT model has 201 different named parameters.

==== Embedding Layer ====

bert.embeddings.word_embeddings.weight                  (92353, 768)
bert.embeddings.position_embeddings.weight                (512, 768)
bert.embeddings.token_type_embeddings.weight                (2, 768)
bert.embeddings.LayerNorm.weight                              (768,)
bert.embeddings.LayerNorm.bias                                (768,)

==== First Transformer ====

bert.encoder.layer.0.attention.self.query.weight          (768, 768)
bert.encoder.layer.0.attention.self.query.bias                (768,)
bert.encoder.layer.0.attention.self.key.weight            (768, 768)
bert.encoder.layer.0.attention.self.key.bias                  (768,)
bert.encoder.layer.0.attention.self.value.weight          (768, 768)
bert.encoder.layer.0.attention.self.value.bias                (768,)
bert.encoder.layer.0.attention.output.dense.weight        (768, 768)
bert.encoder.layer.0.attention.output.dense.bias              (

In [28]:
from transformers import  AdamW
optimizer = AdamW(model.parameters(),
                  lr = 2e-5, # args.learning_rate - default is 5e-5, our notebook had 2e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8.
                )


In [29]:

from transformers import get_linear_schedule_with_warmup

# Number of training epochs (authors recommend between 2 and 4)
epochs = 50

# Total number of training steps is number of batches * number of epochs.
total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0, # Default value in run_glue.py
                                            num_training_steps = total_steps)

In [30]:
import numpy as np

def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

In [31]:
import time
import datetime

def format_time(elapsed):
    '''
    Takes a time in seconds and returns a string hh:mm:ss
    '''
    # Round to the nearest second.
    elapsed_rounded = int(round((elapsed)))
    
    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))


In [32]:
import random
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

# Store the average loss after each epoch so we can plot them.
loss_values = []

# For each epoch...
for epoch_i in range(0, epochs):
    
    # ========================================
    #               Training
    # ========================================
    
    # Perform one full pass over the training set.

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Measure how long the training epoch takes.
    t0 = time.time()

    # Reset the total loss for this epoch.
    total_loss = 0

    # Put the model into training mode. Don't be mislead--the call to 
    # `train` just changes the *mode*, it doesn't *perform* the training.
    # `dropout` and `batchnorm` layers behave differently during training
    # vs. test (source: https://stackoverflow.com/questions/51433378/what-does-model-train-do-in-pytorch)
    model.train()

    # For each batch of training data...
    for step, batch in enumerate(train_dataloader):

        # Progress update every 40 batches.
        if step % 40 == 0 and not step == 0:
            # Calculate elapsed time in minutes.
            elapsed = format_time(time.time() - t0)
            
            # Report progress.
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))


        b_input_ids = batch[0].to(device)
        b_input_mask = batch[1].to(device)
        b_labels = batch[2].to(device)

 
        model.zero_grad()        

        outputs = model(b_input_ids, 
                    token_type_ids=None, 
                    attention_mask=b_input_mask, 
                    labels=b_labels)
        
    
        loss = outputs

        total_loss += loss.item()

        # Perform a backward pass to calculate the gradients.
        loss.backward()

    
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        # Update parameters and take a step using the computed gradient.
        # The optimizer dictates the "update rule"--how the parameters are
        # modified based on their gradients, the learning rate, etc.
        optimizer.step()

        # Update the learning rate.
        scheduler.step()

    # Calculate the average loss over the training data.
    avg_train_loss = total_loss / len(train_dataloader)            
    
    # Store the loss value for plotting the learning curve.
    loss_values.append(avg_train_loss)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epcoh took: {:}".format(format_time(time.time() - t0)))
        
    # # ========================================
    # #               Validation
    # # ========================================
    # # After the completion of each training epoch, measure our performance on
    # # our validation set.

    # print("")
    # print("Running Validation...")

    # t0 = time.time()

    # # Put the model in evaluation mode--the dropout layers behave differently
    # # during evaluation.
    # model.eval()

    # # Tracking variables 
    # eval_loss, eval_accuracy = 0, 0
    # nb_eval_steps, nb_eval_examples = 0, 0

    # # Evaluate data for one epoch
    # for batch in validation_dataloader:
        
    #     # Add batch to GPU
    #     batch = tuple(t.to(device) for t in batch)
        
    #     # Unpack the inputs from our dataloader
    #     b_input_ids, b_input_mask, b_labels = batch
        
    #     # Telling the model not to compute or store gradients, saving memory and
    #     # speeding up validation
    #     with torch.no_grad():        

    #         outputs = model(b_input_ids[0], 
    #                         token_type_ids=None, 
    #                         attention_mask=b_input_mask)
        
    #     # Get the "logits" output by the model. The "logits" are the output
    #     # values prior to applying an activation function like the softmax.
    #     logits = outputs[0]

    #     # Move logits and labels to CPU
    #     logits = logits.detach().cpu().numpy()
    #     label_ids = b_labels.to('cpu').numpy()
        
    #     # Calculate the accuracy for this batch of test sentences.
    #     tmp_eval_accuracy = flat_accuracy(logits, label_ids)
        
    #     # Accumulate the total accuracy.
    #     eval_accuracy += tmp_eval_accuracy

    #     # Track the number of batches
    #     nb_eval_steps += 1

    # # Report the final accuracy for this validation run.
    # print("  Accuracy: {0:.2f}".format(eval_accuracy/nb_eval_steps))
    # print("  Validation took: {:}".format(format_time(time.time() - t0)))

print("")
print("Training complete!")


======== Epoch 1 / 4 ========
Training...


NameError: ignored

In [ ]:
!nvidia-smi